### ISSUE TITLE
I see this when i  run warrior

### ISSUE THREAD

**Issue by kotenok2000** [ArchiveTeam/buzzvideo-grab#1]
Starting CheckIP for Item 
Checking IP address.
Finished CheckIP for Item 
Starting GetItemFromTracker for Item 
Received item 'video:6928607785831629318' from tracker
Starting PrepareDirectories for Item video:6928607785831629318
Finished PrepareDirectories for Item video:6928607785831629318
Starting WgetDownload for Item video:6928607785831629318
Archiving item video:6928607785831629318
1=302 https://www.buzzvideo.com/article/i6928607785831629318 
2=301 https://www.buzzvideo.com/a/6928607785831629318 
3=200 https://www.buzzvideo.com/@%E5%84%80%E4%BA%BA%E9%B6%B4%E6%B2%A2/%E3%81%93%E3%81%AE%E4%BA%BA%E3%80%81%E3%81%86%E3%81%A1%E3%81%AE%E4%BC%9A%E7%A4%BE%E3%81%A7%E3%80%8C%E6%BA%B6%E6%8E%A5%E3%81%AE%E7%A5%9E%E3%80%8D%E3%81%A8%E5%91%BC%E3%81%B0%E3%82%8C%E3%82%8B%E8%81%B7%E4%BA%BA%E3%81%A7%E3%81%99%E3%80%82%E6%BA%B6%E6%8E%A5%E3%83%86%E3%82%AF-BgKAZhJcJ2A 
4=200 https://p16-va.topbuzzcdn.com/list/tos-useast2a-p-0000/adbca23dddf546598027a7a562499e9d 
5=200 https://p16-va.topbuzzcdn.com/origin/tos-useast2a-p-0000/adbca23dddf546598027a7a562499e9d.jpg 
6=200 https://v16.topbuzzcdn.com/530a0fc936c1e5c9d6fb9a7b0cd7312a/6396e8ed/video/tos/useast2a/tos-useast2a-ve-0029/2de0ba139c834d62b8f548031103fd9f/?a=1106&ch=0&cr=0&dr=0&cd=0%7C0%7C0%7C0&cv=1&br=1018&bt=509&cs=0&ds=2&ft=tFFYl8HWoJDr12Nv_hsfZIxRg-MlxQ_45S2&mime_type=video_mp4&qs=0&rc=ZzNlOzo6OTtkaTQ7ZGY1OEBpM2s1OHBwd2tvMzMzNWczM0A0XzMyYmE0Xi8xMWBiYi0vYSNfcmEvLmhva2dgLS0wLjZzcw%3D%3D&l=20221212023655010189052168589063&btag=80000 
7=200 https://www.buzzvideo.com/api/1200/web/comment_v2/comments?brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=6816&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc&item_id=6928607785831629318&group_id=6928607785831629318&media_id=6665151453025386502&count=20&offset= 
8=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=0&category=13&session_impr_id=0&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
9=200 https://www.buzzvideo.com/api/1200/web/comment_v2/detail?brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=6816&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc&item_id=6928607785831629318&group_id=6928607785831629318&media_id=6665151453025386502&count=10&offset=0&comment_id=6933902978738815750 
10=200 https://www.buzzvideo.com/api/1200/web/comment_v2/detail?brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=6816&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc&item_id=6928607785831629318&group_id=6928607785831629318&media_id=6665151453025386502&count=10&offset=0&comment_id=6962861458581357318 
11=200 https://www.buzzvideo.com/api/1200/web/comment_v2/detail?brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=6816&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc&item_id=6928607785831629318&group_id=6928607785831629318&media_id=6665151453025386502&count=10&offset=0&comment_id=6968454443524162309 
12=200 https://www.buzzvideo.com/api/1200/web/comment_v2/detail?brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=6816&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc&item_id=6928607785831629318&group_id=6928607785831629318&media_id=6665151453025386502&count=10&offset=0&comment_id=6946042616479744773 
13=200 https://www.buzzvideo.com/api/1200/web/comment_v2/detail?brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=6816&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc&item_id=6928607785831629318&group_id=6928607785831629318&media_id=6665151453025386502&count=10&offset=0&comment_id=6931936046611432198 
14=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809921.999&category=13&session_impr_id=7176085395821758725&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
15=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809920.99&category=13&session_impr_id=7176085437676079366&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
16=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809919.99&category=13&session_impr_id=7176085437676177670&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
17=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809918.99&category=13&session_impr_id=7176085478863718661&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
18=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809917.99&category=13&session_impr_id=7176085442738964742&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
19=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809916.99&category=13&session_impr_id=7176085476129163525&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
20=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809915.99&category=13&session_impr_id=7176085447139117317&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
21=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809914.99&category=13&session_impr_id=7176085453887588614&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
22=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809913.99&category=13&session_impr_id=7176085447139379461&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
23=200 https://www.buzzvideo.com/api/777/web/stream?category_parameter=6928607785831629318&count=30&max_behot_time=1670809912.99&category=13&session_impr_id=7176085437676914950&brand=dell&dpi=440&resolution=1920*1080&ac=WIFI&os_version=10&version_code=10600&aid=1131&device_brand=dell&manifest_version_code=10600&region=jp&original_channel=pc&device_platform=web&language=ja&youtube=1&app_version=10.6.0&tz_offset=19800&tz_name=Asia%2FJakarta&channel=pc&hevc_supported=1&os=windows&update_version_code=106000&device_type=pc 
queuing for	buzzvideo
found item	video:7110336365459538437
found item	user:6954223807964480518
found item	video:7110569900891980293
found item	video:7116863041798504965
found item	video:7109115765982249477
found item	user:6570518492218916865
found item	video:7109369773389005318
found item	user:6573247264553795594
found item	video:7110142271441437189
found item	video:7110510936716263942
found item	user:6807788329176138757
found item	video:7111125291413537286
found item	user:6397636044891620361
found item	video:7113105442829582853
found item	video:7112615832504599046
found item	video:7111421222159892998
found item	video:7109867009604665861
found item	video:7113008506319749637
found item	video:7115652077019218437
found item	video:7112927128915788294
found item	user:6666739717365710854
found item	video:7112772033385103877
found item	user:6920494177769276421
found item	video:7110187180236014085
found item	video:7112208656267002373
found item	video:7112663549930914310
found item	video:7114895419771060741
found item	video:7174713987224125957
found item	user:6839317830506382341
found item	video:7144118704777806342
found item	video:7115986576240640517
found item	video:7116439674369245702
found item	video:7130556282175504902
found item	user:6701111681164526597
found item	video:7116166315118805510
found item	video:7113762446048854534
found item	user:6924042245424677894
found item	video:7113417823707283973
found item	user:6817670628821894150
found item	video:7110553559309238789
found item	video:7111257358755578374
found item	user:6585749303925882890
found item	video:7172832147122766341
found item	video:7114704108640174597
found item	video:7132107493165007365
found item	user:6624068141628538885
found item	video:7111852675142304262
found item	video:7111833277970842118
found item	video:7114738355820151301
found item	video:7111193252828725766
found item	user:6475083270831735818
found item	video:7112425422800863750
found item	video:7110457762223620614
found item	video:7113550999897784837
found item	video:7114798404626153990
found item	video:7114849518205633029
found item	user:6790057696672039941
found item	video:7130927354091700741
found item	video:7110573819093402117
found item	video:7112804901792793094
found item	video:7112626412338610694
found item	video:7112425606922453509
found item	user:6646311550021156869
found item	video:7110700706125988357
found item	user:6500276720677946378
found item	video:7112235971655074310
found item	video:7112946909236593158
found item	video:7114208528687972870
found item	video:7110857755375796741
found item	video:7114334805394719238
found item	user:6430959895025026057
found item	video:7114733800310997510
found item	video:7114440946665800198
found item	user:6859085765206279173
found item	video:7144334251209638405
found item	video:7110158905874858502
found item	user:6838759144225522694
found item	video:7110107443136627206
found item	video:7112027070305436165
found item	video:7105858614136635910
found item	video:7109473815784210950
found item	video:7175835036057485830
found item	video:7112739605438415365
found item	video:7110446946300576261
found item	video:7119460706868544006
found item	video:7112998996498579973
found item	video:7111136355518169605
found item	video:7161265453900235269
found item	video:7114070399264227845
found item	video:7116116498774753798
found item	video:7115607166278566405
found item	video:7109988526766260741
found item	video:7114338843226046981
found item	video:7112398717478584838
found item	video:7126717006287503877
found item	video:7114701626849509893
found item	video:7104848813508215301
found item	user:6430654889533113353
found item	video:7116103636882620934
found item	video:7110163126414426629
{"data":"100 items queued for deduplication","status_code":200}
found item	video:7111489142378332678
found item	video:7111335075886744070
found item	video:7111462244797825541
found item	video:7114672674877506054
found item	user:6863306315839030278
found item	video:7114424432503882245
found item	video:7109831356800188933
found item	video:7113830265100796421
found item	video:7169898760426963461
found item	video:7110693766633226757
found item	video:7111314274634695173
found item	user:6630782501650759686
found item	user:6501457728303531018
found item	video:7116515494634488325
found item	video:7174150848875119109
found item	video:7119927635563643397
found item	video:7114107781241963014
found item	video:7113436206733574661
found item	user:6543507572287242250
found item	video:7105813564438561286
found item	video:7110166929335124485
found item	video:7145591504533258757
found item	video:7111749915193278981
found item	video:7110759048026259973
found item	video:7112660679777075718
found item	video:7116290055664271877
found item	video:7165437714307842566
found item	video:7112726000290497030
found item	video:7105879959595565574
found item	video:7110088338308121093
found item	video:7114446117567332870
found item	video:7113848653583794693
found item	video:7132813942665363973
found item	video:7109359971598336518
found item	video:7115298734715585029
found item	user:6782083572180599810
{"data":"36 items queued for deduplication","status_code":200}
queuing for	urls
Finished WgetDownload for Item video:6928607785831629318
Starting PrepareStatsForTracker for Item video:6928607785831629318
Finished PrepareStatsForTracker for Item video:6928607785831629318
Starting MoveFiles for Item video:6928607785831629318
Finished MoveFiles for Item video:6928607785831629318
Starting Upload for Item video:6928607785831629318
No item received. There aren't any items available for this project at the moment. Try again later. Retrying after 60 seconds...

**Comment by Arkiver2** [comment]
Looks good?
